[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22.20.0"

[functions]
  directory = "netlify/functions"
  included_files = ["netlify/functions/**"]

# 🔥 Fonksiyon yönlendirmesi
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA yönlendirmesi (en sona koy)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Güvenlik başlıkları (isteğe bağlı)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"